CREATE TABLE usuario (
    id_usuario         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    keycloak_id        VARCHAR(255) NOT NULL UNIQUE,
    email              VARCHAR(255) NOT NULL UNIQUE,
    nombre             VARCHAR(100),
    apellido           VARCHAR(100),
    fecha_registro     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    fecha_ultimo_login TIMESTAMPTZ,
    activo             BOOLEAN      NOT NULL DEFAULT TRUE
);
