-- Esquema para registrar movimientos (ingresos y egresos) mensuales
-- Escrito para PostgreSQL 10+. Todos los id son autoincrementales (IDENTITY).
-- En MySQL: reemplazar "GENERATED BY DEFAULT AS IDENTITY" por "AUTO_INCREMENT".

-- Clasificación: Sueldo, Gasto fijo, Servicios, Tarjeta, Préstamo, Inversión...
CREATE TABLE tipo_movimiento (
    id_tipo_movimiento INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre             VARCHAR(60) NOT NULL UNIQUE,
    naturaleza         CHAR(1)     NOT NULL CHECK (naturaleza IN ('I', 'E')) -- I = ingreso, E = egreso
);

-- Catálogo de conceptos: expensas, luz, etc
CREATE TABLE movimiento (
    id_movimiento      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tipo_movimiento INT          NOT NULL REFERENCES tipo_movimiento(id_tipo_movimiento),
    nombre             VARCHAR(100) NOT NULL UNIQUE,
    descripcion        VARCHAR(255),
    activo             BOOLEAN      NOT NULL DEFAULT TRUE
);

-- Un registro por mes y año (Octubre 2026, Noviembre 2026...)
CREATE TABLE periodo (
    id_periodo INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    anio       SMALLINT NOT NULL,
    mes        SMALLINT NOT NULL CHECK (mes BETWEEN 1 AND 12),
    UNIQUE (anio, mes)
);

-- Columnas "Previsto" y "Real" de cada hoja. Montos siempre positivos:
-- el signo lo da la naturaleza del tipo de movimiento.
CREATE TABLE movimiento_mensual (
    id_movimiento_mensual INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_periodo            INT NOT NULL REFERENCES periodo(id_periodo),
    id_movimiento         INT NOT NULL REFERENCES movimiento(id_movimiento),
    monto_previsto        NUMERIC(14,2) CHECK (monto_previsto >= 0),
    monto_real            NUMERIC(14,2) CHECK (monto_real >= 0),
    nro_cuota             SMALLINT,          -- ej. 9 en "Préstamo galicia (9/12)"
    total_cuotas          SMALLINT,          -- ej. 12
    notas                 VARCHAR(255),
    UNIQUE (id_periodo, id_movimiento)
);

-- Columna "Final": simulaciones. Un mes puede tener varias.
CREATE TABLE escenario (
    id_escenario INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_periodo   INT          NOT NULL REFERENCES periodo(id_periodo),
    nombre       VARCHAR(100) NOT NULL,
    descripcion  VARCHAR(255),
    UNIQUE (id_periodo, nombre)
);

-- Qué movimientos entran en cada simulación y con qué monto.
-- Si un gasto no está en la tabla, no cuenta en ese escenario.
CREATE TABLE escenario_detalle (
    id_escenario_detalle INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_escenario         INT NOT NULL REFERENCES escenario(id_escenario) ON DELETE CASCADE,
    id_movimiento        INT NOT NULL REFERENCES movimiento(id_movimiento),
    monto                NUMERIC(14,2) NOT NULL CHECK (monto >= 0),
    UNIQUE (id_escenario, id_movimiento)
);


